var margin = 20,
    diameter = 960;

var color = d3.scale.linear()
    .domain([-1, 5])
    .range(["hsl(152,80%,80%)", "hsl(228,30%,40%)"])
    .interpolate(d3.interpolateHcl);

var pack = d3.layout.pack()
    .padding(2)
    .size([diameter - margin, diameter - margin])
    .value(function(d) { return d.size; })

var svg = d3.select("body").append("svg")
    .attr("width", diameter)
    .attr("height", diameter)
  .append("g")
    .attr("transform", "translate(" + diameter / 2 + "," + diameter / 2 + ")");

var root = getData();

  var focus = root,
      nodes = pack.nodes(root),
      view;

  var circle = svg.selectAll("circle")
      .data(nodes)
    .enter().append("circle")
      .attr("class", function(d) { return d.parent ? d.children ? "node" : "node node--leaf" : "node node--root"; })
      .style("fill", function(d) { return d.children ? color(d.depth) : null; })
      .on("click", function(d) { if (focus !== d) zoom(d), d3.event.stopPropagation(); });

  var text = svg.selectAll("text")
      .data(nodes)
    .enter().append("text")
      .attr("class", "label")
      .style("fill-opacity", function(d) { return d.parent === root ? 1 : 0; })
      .style("display", function(d) { return d.parent === root ? null : "none"; })
      .text(function(d) { return d.name; });

  var node = svg.selectAll("circle,text");

  d3.select("body")
      .style("background", color(-1))
      .on("click", function() { zoom(root); });

  zoomTo([root.x, root.y, root.r * 2 + margin]);

  function zoom(d) {
    var focus0 = focus; focus = d;

    var transition = d3.transition()
        .duration(d3.event.altKey ? 7500 : 750)
        .tween("zoom", function(d) {
          var i = d3.interpolateZoom(view, [focus.x, focus.y, focus.r * 2 + margin]);
          return function(t) { zoomTo(i(t)); };
        });

    transition.selectAll("text")
      .filter(function(d) { return d.parent === focus || this.style.display === "inline"; })
        .style("fill-opacity", function(d) { return d.parent === focus ? 1 : 0; })
        .each("start", function(d) { if (d.parent === focus) this.style.display = "inline"; })
        .each("end", function(d) { if (d.parent !== focus) this.style.display = "none"; });
  }
  function zoomTo(v) {
    var k = diameter / v[2]; view = v;
    node.attr("transform", function(d) { return "translate(" + (d.x - v[0]) * k + "," + (d.y - v[1]) * k + ")"; });
    circle.attr("r", function(d) { return d.r * k; });

};

function getData() {
    return {
        'children': [{'children': [{'children': [{'name': 'Cristiano Ronaldo',
       'size': 94},
      {'name': 'Pepe', 'size': 86},
      {'name': 'Bernardo Silva', 'size': 84},
      {'name': 'Rui Patrício', 'size': 83},
      {'name': 'Adrien Silva', 'size': 83},
      {'name': 'João Mário', 'size': 83},
      {'name': 'Quaresma', 'size': 83},
      {'name': 'Nani', 'size': 83},
      {'name': 'A. Lopes', 'size': 83},
      {'name': 'Danilo Pereira', 'size': 83},
      {'name': 'William Carvalho', 'size': 83},
      {'name': 'João Moutinho', 'size': 82},
      {'name': 'André Gomes', 'size': 82},
      {'name': 'Pizzi', 'size': 82},
      {'name': 'Bruma', 'size': 81},
      {'name': 'Nélson Semedo', 'size': 81},
      {'name': 'Gelson Martins', 'size': 81},
      {'name': 'R. Guerreiro', 'size': 81},
      {'name': 'Daniel Carriço', 'size': 80},
      {'name': 'Manuel Fernandes', 'size': 80},
      {'name': 'Ricardo Pereira', 'size': 80},
      {'name': 'Antunes', 'size': 79},
      {'name': 'José Fonte', 'size': 79},
      {'name': 'Cédric', 'size': 79},
      {'name': 'João Cancelo', 'size': 79},
      {'name': 'Bruno Alves', 'size': 78},
      {'name': 'Paulo Oliveira', 'size': 78},
      {'name': 'Bruno Fernandes', 'size': 78},
      {'name': 'Bruno Fernandes', 'size': 78},
      {'name': 'Iuri Medeiros', 'size': 78},
      {'name': 'Paulo Oliveira', 'size': 78},
      {'name': 'Miguel Lopes', 'size': 78},
      {'name': 'Marafona', 'size': 78},
      {'name': 'André Silva', 'size': 78},
      {'name': 'André André', 'size': 78},
      {'name': 'Rafa', 'size': 78},
      {'name': 'Rafa', 'size': 78},
      {'name': 'André André', 'size': 78},
      {'name': 'Hernâni', 'size': 78},
      {'name': 'Hernâni', 'size': 78},
      {'name': 'Pedro Santos', 'size': 78},
      {'name': 'Pedro Santos', 'size': 78},
      {'name': 'Eliseu', 'size': 78},
      {'name': 'Vieirinha', 'size': 77},
      {'name': 'Luisinho', 'size': 77},
      {'name': 'Bruno Varela', 'size': 77},
      {'name': 'Ricardo Ferreira', 'size': 77}],
     'name': 'Portugal'},
    {'children': [{'name': 'M. Neuer', 'size': 92},
      {'name': 'T. Kroos', 'size': 90},
      {'name': 'M. Özil', 'size': 88},
      {'name': 'J. Boateng', 'size': 88},
      {'name': 'M. Hummels', 'size': 88},
      {'name': 'T. Müller', 'size': 86},
      {'name': 'M. Reus', 'size': 86},
      {'name': 'I. Gündoğan', 'size': 85},
      {'name': 'M. ter Stegen', 'size': 85},
      {'name': 'B. Leno', 'size': 85},
      {'name': 'S. Mustafi', 'size': 84},
      {'name': 'T. Horn', 'size': 84},
      {'name': 'J. Draxler', 'size': 84},
      {'name': 'R. Fährmann', 'size': 84},
      {'name': 'S. Khedira', 'size': 84},
      {'name': 'B. Höwedes', 'size': 83},
      {'name': 'N. Süle', 'size': 83},
      {'name': 'G. Castro', 'size': 82},
      {'name': 'M. Kruse', 'size': 82},
      {'name': 'A. Rüdiger', 'size': 82},
      {'name': 'K. Trapp', 'size': 82},
      {'name': 'M. Gómez', 'size': 82},
      {'name': 'L. Stindl', 'size': 82},
      {'name': 'K. Bellarabi', 'size': 82},
      {'name': 'J. Tah', 'size': 82},
      {'name': 'T. Werner', 'size': 82},
      {'name': 'L. Goretzka', 'size': 82},
      {'name': 'O. Baumann', 'size': 82},
      {'name': 'L. Sané', 'size': 82},
      {'name': 'L. Bender', 'size': 82},
      {'name': 'M. Götze', 'size': 81},
      {'name': 'S. Rudy', 'size': 81},
      {'name': 'B. Schweinsteiger', 'size': 81},
      {'name': 'J. Weigl', 'size': 81},
      {'name': 'J. Kimmich', 'size': 81},
      {'name': 'S. Bender', 'size': 80},
      {'name': 'K. Vogt', 'size': 80},
      {'name': 'L. Podolski', 'size': 80},
      {'name': 'A. Schürrle', 'size': 80},
      {'name': 'M. Schmelzer', 'size': 80},
      {'name': 'D. Didavi', 'size': 80},
      {'name': 'E. Can', 'size': 80},
      {'name': 'J. Hector', 'size': 80},
      {'name': 'L. Karius', 'size': 80},
      {'name': 'J. Brandt', 'size': 80},
      {'name': 'K. Demirbay', 'size': 80},
      {'name': 'K. Volland', 'size': 80},
      {'name': 'R. Zieler', 'size': 79},
      {'name': 'S. Tasci', 'size': 79},
      {'name': 'S. Wagner', 'size': 79},
      {'name': 'B. Hübner', 'size': 79},
      {'name': 'D. Baier', 'size': 79},
      {'name': 'R. Adler', 'size': 79},
      {'name': 'P. Herrmann', 'size': 79},
      {'name': 'C. Kramer', 'size': 79},
      {'name': 'W. Orban', 'size': 79},
      {'name': 'M. Meyer', 'size': 79},
      {'name': 'M. Dahoud', 'size': 79},
      {'name': 'M. Arnold', 'size': 79},
      {'name': 'S. Gnabry', 'size': 79},
      {'name': 'D. Heintz', 'size': 78},
      {'name': 'D. Heintz', 'size': 78},
      {'name': 'L. Bittencourt', 'size': 78},
      {'name': 'S. Rode', 'size': 78},
      {'name': 'M. Höger', 'size': 78},
      {'name': 'M. Höger', 'size': 78},
      {'name': 'M. Ginter', 'size': 78},
      {'name': 'M. Ginter', 'size': 78},
      {'name': 'N. Stark', 'size': 78},
      {'name': 'M. Weiser', 'size': 78},
      {'name': 'M. Weiser', 'size': 78},
      {'name': 'M. Weiser', 'size': 78},
      {'name': 'M. Weiser', 'size': 78},
      {'name': 'N. Stark', 'size': 78},
      {'name': 'D. Demme', 'size': 78},
      {'name': 'N. Stark', 'size': 78},
      {'name': 'N. Stark', 'size': 78},
      {'name': 'D. Latza', 'size': 77},
      {'name': 'J. Hofmann', 'size': 77},
      {'name': 'A. Younes', 'size': 77},
      {'name': 'A. Meier', 'size': 77},
      {'name': 'E. Durm', 'size': 77},
      {'name': 'J. Geis', 'size': 77},
      {'name': 'S. Bell', 'size': 77},
      {'name': 'S. Terodde', 'size': 77}],
     'name': 'Germany'},
    {'children': [{'name': 'R. Lewandowski', 'size': 91},
      {'name': 'K. Glik', 'size': 85},
      {'name': 'L. Piszczek', 'size': 83},
      {'name': 'W. Szczęsny', 'size': 82},
      {'name': 'G. Krychowiak', 'size': 81},
      {'name': 'L. Fabiański', 'size': 80},
      {'name': 'P. Zieliński', 'size': 80},
      {'name': 'A. Milik', 'size': 79},
      {'name': 'L. Teodorczyk', 'size': 78},
      {'name': 'A. Boruc', 'size': 77}],
     'name': 'Poland'},
    {'children': [{'name': 'De Gea', 'size': 90},
      {'name': 'Sergio Ramos', 'size': 90},
      {'name': 'Thiago', 'size': 88},
      {'name': 'Iniesta', 'size': 87},
      {'name': 'Piqué', 'size': 87},
      {'name': 'David Silva', 'size': 87},
      {'name': 'Cesc Fàbregas', 'size': 86},
      {'name': 'Diego Costa', 'size': 86},
      {'name': 'Sergio Busquets', 'size': 86},
      {'name': 'Isco', 'size': 86},
      {'name': 'Javi Martínez', 'size': 86},
      {'name': 'Azpilicueta', 'size': 85},
      {'name': 'Jordi Alba', 'size': 85},
      {'name': 'Morata', 'size': 84},
      {'name': 'Aduriz', 'size': 84},
      {'name': 'Juan Mata', 'size': 84},
      {'name': 'Ander Herrera', 'size': 84},
      {'name': 'Sergio Asenjo', 'size': 84},
      {'name': 'Carvajal', 'size': 84},
      {'name': 'Bruno', 'size': 84},
      {'name': 'Pedro', 'size': 84},
      {'name': 'Koke', 'size': 84},
      {'name': 'Marco Asensio', 'size': 84},
      {'name': 'José Callejón', 'size': 83},
      {'name': 'Borja Valero', 'size': 83},
      {'name': 'Juanfran', 'size': 83},
      {'name': 'Diego López', 'size': 83},
      {'name': 'Casillas', 'size': 83},
      {'name': 'José Reina', 'size': 83},
      {'name': 'Vitolo', 'size': 83},
      {'name': 'Parejo', 'size': 83},
      {'name': 'Iago Aspas', 'size': 83},
      {'name': 'Santi Cazorla', 'size': 83},
      {'name': 'David Villa', 'size': 82},
      {'name': 'Beñat', 'size': 82},
      {'name': 'Roque Mesa', 'size': 82},
      {'name': 'Iborra', 'size': 82},
      {'name': 'Deulofeu', 'size': 82},
      {'name': 'Sergio Rico', 'size': 82},
      {'name': 'Saúl', 'size': 82},
      {'name': 'Raúl Albiol', 'size': 82},
      {'name': 'Manu Trigueros', 'size': 82},
      {'name': 'Suso', 'size': 82},
      {'name': 'Lucas Vázquez', 'size': 82},
      {'name': 'Iñigo Martínez', 'size': 82},
      {'name': 'Víctor Ruíz', 'size': 82},
      {'name': 'Illarramendi', 'size': 81},
      {'name': 'Camacho', 'size': 81},
      {'name': 'Marcos Alonso', 'size': 81},
      {'name': 'Moyá', 'size': 81},
      {'name': 'Fernando Torres', 'size': 81},
      {'name': 'Gabi', 'size': 81},
      {'name': 'Raúl García', 'size': 81},
      {'name': 'Iturraspe', 'size': 81},
      {'name': 'Lucas Pérez', 'size': 81},
      {'name': 'Dani García', 'size': 81},
      {'name': 'Williams', 'size': 81},
      {'name': 'De Marcos', 'size': 81},
      {'name': 'Adán', 'size': 81},
      {'name': 'Sergi Roberto', 'size': 81},
      {'name': 'Mario Gaspar', 'size': 81},
      {'name': 'Nacho Fernández', 'size': 81},
      {'name': 'Bartra', 'size': 81},
      {'name': 'Héctor Bellerín', 'size': 81},
      {'name': 'Iago Falqué', 'size': 80},
      {'name': 'Nacho Monreal', 'size': 80},
      {'name': 'Kiko Casilla', 'size': 80},
      {'name': 'Pedro León', 'size': 80},
      {'name': 'Coke', 'size': 80},
      {'name': 'Javi Fuego', 'size': 80},
      {'name': 'Sergi Enrich', 'size': 80},
      {'name': 'Mikel San José', 'size': 80},
      {'name': 'Hugo Mallo', 'size': 80},
      {'name': 'Denis Suárez', 'size': 80},
      {'name': 'Grimaldo', 'size': 80},
      {'name': 'Samu Castillejo', 'size': 80},
      {'name': 'Arrizabalaga', 'size': 80},
      {'name': 'Marcano', 'size': 80},
      {'name': 'Pablo Sarabia', 'size': 80},
      {'name': 'Bernat', 'size': 79},
      {'name': 'Paco Alcácer', 'size': 79},
      {'name': 'Escudero', 'size': 79},
      {'name': 'Jaume Costa', 'size': 79},
      {'name': 'Nolito', 'size': 79},
      {'name': 'Balenziaga', 'size': 79},
      {'name': 'Canales', 'size': 79},
      {'name': 'Adrián', 'size': 79},
      {'name': 'Oriol Romeu', 'size': 79},
      {'name': 'Keko', 'size': 79},
      {'name': 'Diego Llorente', 'size': 79},
      {'name': 'Jurado', 'size': 79},
      {'name': 'Negredo', 'size': 79},
      {'name': 'Rubén Pardo', 'size': 79},
      {'name': 'Roberto', 'size': 79},
      {'name': 'Oyarzabal', 'size': 79},
      {'name': 'Fabricio', 'size': 79},
      {'name': 'Bojan', 'size': 79},
      {'name': 'Gerard Moreno', 'size': 79},
      {'name': 'Gayà', 'size': 79},
      {'name': 'Óliver Torres', 'size': 79},
      {'name': 'Vicente Gómez', 'size': 79},
      {'name': 'Bigas', 'size': 78},
      {'name': 'Pozuelo', 'size': 78},
      {'name': 'Pozuelo', 'size': 78},
      {'name': 'Bigas', 'size': 78},
      {'name': 'Javi García', 'size': 78},
      {'name': 'Fontàs', 'size': 78},
      {'name': 'Carles Gil', 'size': 78},
      {'name': 'Carles Gil', 'size': 78},
      {'name': 'Jorge Meré', 'size': 78},
      {'name': 'Pau López', 'size': 78},
      {'name': 'Pau López', 'size': 78},
      {'name': 'Granero', 'size': 78},
      {'name': 'Jony', 'size': 78},
      {'name': 'Jony', 'size': 78},
      {'name': 'Raúl Navas', 'size': 78},
      {'name': 'Raúl Navas', 'size': 78},
      {'name': 'Dani Ceballos', 'size': 78},
      {'name': 'Rodrigo', 'size': 78},
      {'name': 'Yeray', 'size': 78},
      {'name': 'Morales', 'size': 78},
      {'name': 'Mosquera', 'size': 78},
      {'name': 'Joaquín', 'size': 78},
      {'name': 'Juanfran', 'size': 78},
      {'name': 'Muniain', 'size': 78},
      {'name': 'Morales', 'size': 78},
      {'name': 'Rodrigo', 'size': 78},
      {'name': 'Sergi Darder', 'size': 78},
      {'name': 'Susaeta', 'size': 78},
      {'name': 'Borja Bastón', 'size': 78},
      {'name': 'Capa', 'size': 78},
      {'name': 'David López', 'size': 78},
      {'name': 'Capa', 'size': 78},
      {'name': 'Sergi Darder', 'size': 78},
      {'name': 'Rochina', 'size': 78},
      {'name': 'Sergi Gómez', 'size': 77},
      {'name': 'Recio', 'size': 77},
      {'name': 'David García', 'size': 77},
      {'name': 'Aritz Elustondo', 'size': 77},
      {'name': 'Timor', 'size': 77},
      {'name': 'Javi Varas', 'size': 77},
      {'name': 'Sandro', 'size': 77}],
     'name': 'Spain'},
    {'children': [{'name': 'E. Hazard', 'size': 90},
      {'name': 'T. Courtois', 'size': 89},
      {'name': 'K. De Bruyne', 'size': 89},
      {'name': 'R. Nainggolan', 'size': 86},
      {'name': 'T. Alderweireld', 'size': 86},
      {'name': 'R. Lukaku', 'size': 86},
      {'name': 'D. Mertens', 'size': 86},
      {'name': 'V. Kompany', 'size': 85},
      {'name': 'Y. Carrasco', 'size': 85},
      {'name': 'J. Vertonghen', 'size': 85},
      {'name': 'M. Dembélé', 'size': 83},
      {'name': 'A. Witsel', 'size': 82},
      {'name': 'S. Mignolet', 'size': 81},
      {'name': 'C. Benteke', 'size': 81},
      {'name': 'K. Mirallas', 'size': 81},
      {'name': 'T. Meunier', 'size': 81},
      {'name': 'Y. Tielemans', 'size': 80},
      {'name': 'T. Hazard', 'size': 80},
      {'name': 'M. Batshuayi', 'size': 80},
      {'name': 'M. Fellaini', 'size': 79},
      {'name': 'L. Dendoncker', 'size': 79},
      {'name': 'D. Origi', 'size': 78},
      {'name': 'D. Origi', 'size': 78},
      {'name': 'N. Chadli', 'size': 78},
      {'name': 'T. Bongonda', 'size': 78},
      {'name': 'G. Gillet', 'size': 78},
      {'name': 'N. Lombaerts', 'size': 78},
      {'name': 'K. Casteels', 'size': 78},
      {'name': 'J. Lukaku', 'size': 77},
      {'name': 'J. Van Damme', 'size': 77}],
     'name': 'Belgium'},
    {'children': [{'name': 'L. Modrić', 'size': 89},
      {'name': 'I. Rakitić', 'size': 87},
      {'name': 'D. Subašić', 'size': 85},
      {'name': 'I. Perišić', 'size': 84},
      {'name': 'M. Mandžukić', 'size': 83},
      {'name': 'V. Ćorluka', 'size': 82},
      {'name': 'M. Kovačić', 'size': 82},
      {'name': 'M. Brozović', 'size': 81},
      {'name': 'A. Kramarić', 'size': 81},
      {'name': 'D. Lovren', 'size': 81},
      {'name': 'N. Kalinić', 'size': 81},
      {'name': 'S. Vrsaljko', 'size': 79},
      {'name': 'M. Badelj', 'size': 78},
      {'name': 'M. Badelj', 'size': 78}],
     'name': 'Croatia'},
    {'children': [{'name': 'G. Buffon', 'size': 89},
      {'name': 'G. Chiellini', 'size': 89},
      {'name': 'L. Bonucci', 'size': 88},
      {'name': 'M. Verratti', 'size': 87},
      {'name': 'A. Barzagli', 'size': 85},
      {'name': 'C. Marchisio', 'size': 85},
      {'name': 'L. Insigne', 'size': 85},
      {'name': 'D. De Rossi', 'size': 83},
      {'name': 'S. Giovinco', 'size': 83},
      {'name': 'A. Belotti', 'size': 83},
      {'name': 'G. Bonaventura', 'size': 83},
      {'name': 'M. Perin', 'size': 83},
      {'name': 'A. Consigli', 'size': 82},
      {'name': 'F. Acerbi', 'size': 82},
      {'name': 'F. Vázquez', 'size': 82},
      {'name': 'M. Balotelli', 'size': 82},
      {'name': 'F. Bernardeschi', 'size': 82},
      {'name': 'G. Donnarumma', 'size': 82},
      {'name': 'A. Florenzi', 'size': 82},
      {'name': 'C. Immobile', 'size': 82},
      {'name': 'E. Viviano', 'size': 82},
      {'name': 'M. Parolo', 'size': 81},
      {'name': 'D. Astori', 'size': 81},
      {'name': 'D. Berardi', 'size': 81},
      {'name': 'Jorginho', 'size': 81},
      {'name': 'S. Zaza', 'size': 81},
      {'name': 'D. Berardi', 'size': 81},
      {'name': 'Eder', 'size': 80},
      {'name': 'R. Soriano', 'size': 80},
      {'name': 'M. Darmian', 'size': 80},
      {'name': 'F. Marchetti', 'size': 80},
      {'name': 'A. Mirante', 'size': 80},
      {'name': 'D. Criscito', 'size': 80},
      {'name': 'S. El Shaarawy', 'size': 80},
      {'name': 'A. Candreva', 'size': 80},
      {'name': 'D. Rugani', 'size': 80},
      {'name': 'M. Gabbiadini', 'size': 79},
      {'name': 'R. Saponara', 'size': 79},
      {'name': 'A. Ogbonna', 'size': 79},
      {'name': 'A. Romagnoli', 'size': 79},
      {'name': 'S. Sorrentino', 'size': 79},
      {'name': 'M. Benassi', 'size': 79},
      {'name': 'L. Tonelli', 'size': 79},
      {'name': 'S. Sirigu', 'size': 79},
      {'name': 'D. Baselli', 'size': 79},
      {'name': 'D. Zappacosta', 'size': 79},
      {'name': 'N. Sansone', 'size': 79},
      {'name': 'M. Borriello', 'size': 78},
      {'name': 'S. Verdi', 'size': 78},
      {'name': 'R. Gagliardini', 'size': 78},
      {'name': 'R. Gagliardini', 'size': 78},
      {'name': 'D. Caligiuri', 'size': 78},
      {'name': 'D. Caligiuri', 'size': 78},
      {'name': 'M. Sportiello', 'size': 78},
      {'name': 'M. Valdifiori', 'size': 77},
      {'name': 'F. Magnanelli', 'size': 77},
      {'name': 'S. Okaka', 'size': 77},
      {'name': 'S. Sturaro', 'size': 77},
      {'name': 'A. Gamberini', 'size': 77}],
     'name': 'Italy'},
    {'children': [{'name': 'G. Bale', 'size': 89},
      {'name': 'A. Williams', 'size': 82},
      {'name': 'A. Ramsey', 'size': 82},
      {'name': 'B. Davies', 'size': 78}],
     'name': 'Wales'},
    {'children': [{'name': 'Z. Ibrahimović', 'size': 88},
      {'name': 'E. Forsberg', 'size': 83},
      {'name': 'M. Berg', 'size': 80},
      {'name': 'A. Granqvist', 'size': 80},
      {'name': 'V. Lindelöf', 'size': 79},
      {'name': 'V. Lindelöf', 'size': 79},
      {'name': 'P. Wernbloom', 'size': 79},
      {'name': 'J. Guidetti', 'size': 78},
      {'name': 'J. Guidetti', 'size': 78},
      {'name': 'P. Jansson', 'size': 77}],
     'name': 'Sweden'},
    {'children': [{'name': 'H. Lloris', 'size': 88},
      {'name': 'A. Griezmann', 'size': 88},
      {'name': 'P. Pogba', 'size': 87},
      {'name': 'N. Kanté', 'size': 87},
      {'name': 'F. Ribéry', 'size': 86},
      {'name': 'K. Benzema', 'size': 86},
      {'name': 'B. Matuidi', 'size': 85},
      {'name': 'S. Ruffier', 'size': 85},
      {'name': 'A. Lacazette', 'size': 85},
      {'name': 'R. Varane', 'size': 85},
      {'name': 'L. Koscielny', 'size': 84},
      {'name': 'D. Payet', 'size': 84},
      {'name': 'A. Laporte', 'size': 84},
      {'name': 'M. Schneiderlin', 'size': 83},
      {'name': "S. N'Zonzi", 'size': 83},
      {'name': 'K. Gameiro', 'size': 83},
      {'name': 'O. Dembélé', 'size': 83},
      {'name': 'S. Umtiti', 'size': 83},
      {'name': 'L. Perrin', 'size': 83},
      {'name': 'K. Mbappé', 'size': 83},
      {'name': 'T. Lemar', 'size': 83},
      {'name': 'T. Bakayoko', 'size': 82},
      {'name': 'O. Giroud', 'size': 82},
      {'name': 'S. Mandanda', 'size': 82},
      {'name': 'B. Costil', 'size': 82},
      {'name': 'N. Fekir', 'size': 82},
      {'name': 'A. Martial', 'size': 82},
      {'name': 'C. Tolisso', 'size': 82},
      {'name': 'F. Thauvin', 'size': 82},
      {'name': 'A. Rami', 'size': 81},
      {'name': 'A. Gignac', 'size': 81},
      {'name': 'M. Valbuena', 'size': 81},
      {'name': 'H. Ben Arfa', 'size': 81},
      {'name': 'C. Carrasso', 'size': 81},
      {'name': 'M. Sakho', 'size': 81},
      {'name': 'M. Sanson', 'size': 81},
      {'name': 'A. Rabiot', 'size': 81},
      {'name': 'W. Ben Yedder', 'size': 81},
      {'name': 'M. Gonalons', 'size': 80},
      {'name': 'R. Thomas', 'size': 80},
      {'name': 'V. Germain', 'size': 80},
      {'name': 'L. Kurzawa', 'size': 80},
      {'name': 'A. Pléa', 'size': 80},
      {'name': 'J. Mathieu', 'size': 80},
      {'name': 'P. Evra', 'size': 80},
      {'name': 'J. Guilavogui', 'size': 80},
      {'name': 'L. Digne', 'size': 79},
      {'name': 'D. Sidibé', 'size': 79},
      {'name': 'F. Lejeune', 'size': 79},
      {'name': 'W. Cyprien', 'size': 79},
      {'name': 'K. Zouma', 'size': 79},
      {'name': 'D. Zurutuza', 'size': 79},
      {'name': 'W. Vainqueur', 'size': 79},
      {'name': 'C. Lenglet', 'size': 79},
      {'name': 'F. Coquelin', 'size': 79},
      {'name': 'K. Coman', 'size': 79},
      {'name': 'B. Gomis', 'size': 79},
      {'name': 'P. Ntep', 'size': 79},
      {'name': 'Y. Cardinale', 'size': 79},
      {'name': 'S. Corchia', 'size': 79},
      {'name': 'A. Areola', 'size': 79},
      {'name': 'B. Reynet', 'size': 78},
      {'name': 'B. Reynet', 'size': 78},
      {'name': 'V. Eysseric', 'size': 78},
      {'name': 'V. Eysseric', 'size': 78},
      {'name': 'Y. Gourcuff', 'size': 78},
      {'name': 'R. Hamouma', 'size': 78},
      {'name': 'M. Niang', 'size': 78},
      {'name': 'T. Mangani', 'size': 78},
      {'name': 'T. Mangani', 'size': 78},
      {'name': 'V. Koziello', 'size': 78},
      {'name': 'V. Koziello', 'size': 78},
      {'name': 'L. Tousart', 'size': 78},
      {'name': 'L. Tousart', 'size': 78},
      {'name': 'V. Rongier', 'size': 78},
      {'name': 'V. Rongier', 'size': 78},
      {'name': "Y. M'Vila", 'size': 78},
      {'name': 'B. Mendy', 'size': 78},
      {'name': 'B. Lecomte', 'size': 78},
      {'name': 'A. Doucouré', 'size': 78},
      {'name': 'B. André', 'size': 77},
      {'name': 'G. Clichy', 'size': 77},
      {'name': 'M. Debuchy', 'size': 77},
      {'name': 'G. Defrel', 'size': 77},
      {'name': 'Y. Sabaly', 'size': 77}],
     'name': 'France'},
    {'children': [{'name': 'A. Robben', 'size': 88},
      {'name': 'K. Strootman', 'size': 84},
      {'name': 'B. Dost', 'size': 83},
      {'name': 'S. de Vrij', 'size': 83},
      {'name': 'V. van Dijk', 'size': 83},
      {'name': 'G. Wijnaldum', 'size': 82},
      {'name': 'D. Klaassen', 'size': 82},
      {'name': 'Q. Promes', 'size': 82},
      {'name': 'J. Cillessen', 'size': 81},
      {'name': 'D. Blind', 'size': 80},
      {'name': 'J. Lens', 'size': 80},
      {'name': 'M. Depay', 'size': 79},
      {'name': 'B. Martins Indi', 'size': 79},
      {'name': 'J. Bruma', 'size': 79},
      {'name': 'J. Zoet', 'size': 79},
      {'name': 'R. Karsdorp', 'size': 78},
      {'name': 'R. van Persie', 'size': 78},
      {'name': 'K. Vermeer', 'size': 78},
      {'name': 'T. Vilhena', 'size': 78},
      {'name': 'I. Afellay', 'size': 78},
      {'name': 'M. van Ginkel', 'size': 78},
      {'name': 'V. Janssen', 'size': 77},
      {'name': 'D. Pröpper', 'size': 77},
      {'name': 'J. Veltman', 'size': 77},
      {'name': 'J. De Guzmán', 'size': 77},
      {'name': 'L. Fer', 'size': 77},
      {'name': 'W. Hoedt', 'size': 77},
      {'name': 'J. Toornstra', 'size': 77},
      {'name': 'P. Verhaegh', 'size': 77},
      {'name': 'T. Kongolo', 'size': 77}],
     'name': 'Netherlands'},
    {'children': [{'name': 'J. Oblak', 'size': 88},
      {'name': 'S. Handanovič', 'size': 87},
      {'name': 'K. Kampl', 'size': 81},
      {'name': 'V. Birsa', 'size': 80},
      {'name': 'J. Iličić', 'size': 80}],
     'name': 'Slovenia'},
    {'children': [{'name': 'C. Eriksen', 'size': 87},
      {'name': 'K. Schmeichel', 'size': 83},
      {'name': 'A. Christensen', 'size': 81},
      {'name': 'S. Kjær', 'size': 81},
      {'name': 'D. Wass', 'size': 80},
      {'name': 'M. Krohn-Dehli', 'size': 79},
      {'name': 'N. Jørgensen', 'size': 79},
      {'name': 'J. Vestergaard', 'size': 79},
      {'name': 'K. Dolberg', 'size': 78},
      {'name': 'L. Schøne', 'size': 77},
      {'name': 'F. Sørensen', 'size': 77}],
     'name': 'Denmark'},
    {'children': [{'name': 'M. Hamšík', 'size': 87},
      {'name': 'M. Škrtel', 'size': 81},
      {'name': 'J. Kucka', 'size': 79}],
     'name': 'Slovakia'},
    {'children': [{'name': 'D. Alaba', 'size': 86},
      {'name': 'M. Arnautović', 'size': 82},
      {'name': 'Z. Junuzović', 'size': 79},
      {'name': 'S. Prödl', 'size': 79},
      {'name': 'J. Baumgartlinger', 'size': 78},
      {'name': 'M. Sabitzer', 'size': 78},
      {'name': 'M. Sabitzer', 'size': 78},
      {'name': 'K. Wimmer', 'size': 78},
      {'name': 'M. Hinteregger', 'size': 77}],
     'name': 'Austria'},
    {'children': [{'name': 'Sokratis', 'size': 86},
      {'name': 'K. Manolas', 'size': 84},
      {'name': 'O. Karnezis', 'size': 82},
      {'name': 'K. Mitroglou', 'size': 81},
      {'name': 'K. Papadopoulos', 'size': 79},
      {'name': 'J. Holebas', 'size': 78},
      {'name': 'A. Samaris', 'size': 78},
      {'name': 'K. Fortounis', 'size': 78},
      {'name': 'K. Fortounis', 'size': 78},
      {'name': 'S. Kapino', 'size': 77}],
     'name': 'Greece'},
    {'children': [{'name': 'H. Kane', 'size': 86},
      {'name': 'D. Alli', 'size': 84},
      {'name': 'G. Cahill', 'size': 84},
      {'name': 'A. Lallana', 'size': 83},
      {'name': 'K. Walker', 'size': 83},
      {'name': 'J. Henderson', 'size': 82},
      {'name': 'D. Sturridge', 'size': 82},
      {'name': 'D. Rose', 'size': 82},
      {'name': 'N. Clyne', 'size': 82},
      {'name': 'E. Dier', 'size': 82},
      {'name': 'L. Baines', 'size': 82},
      {'name': 'R. Sterling', 'size': 82},
      {'name': 'J. Wilshere', 'size': 81},
      {'name': 'C. Smalling', 'size': 81},
      {'name': 'M. Keane', 'size': 81},
      {'name': 'W. Rooney', 'size': 81},
      {'name': 'T. Heaton', 'size': 81},
      {'name': 'R. Barkley', 'size': 81},
      {'name': 'J. Vardy', 'size': 81},
      {'name': 'J. Butland', 'size': 81},
      {'name': 'P. Jagielka', 'size': 80},
      {'name': 'T. Walcott', 'size': 80},
      {'name': 'R. Bertrand', 'size': 80},
      {'name': 'J. Milner', 'size': 80},
      {'name': 'M. Antonio', 'size': 80},
      {'name': 'D. Welbeck', 'size': 80},
      {'name': 'M. Rashford', 'size': 80},
      {'name': 'A. Oxlade-Chamberlain', 'size': 80},
      {'name': 'R. Shawcross', 'size': 79},
      {'name': 'L. Shaw', 'size': 79},
      {'name': 'P. Jones', 'size': 79},
      {'name': 'G. Barry', 'size': 79},
      {'name': 'D. Drinkwater', 'size': 79},
      {'name': 'J. Stones', 'size': 79},
      {'name': 'A. Townsend', 'size': 78},
      {'name': 'J. Terry', 'size': 78},
      {'name': 'J. Cork', 'size': 78},
      {'name': 'J. Cork', 'size': 78},
      {'name': 'J. Ward-Prowse', 'size': 78},
      {'name': 'C. Austin', 'size': 78},
      {'name': 'J. Lingard', 'size': 78},
      {'name': 'S. Dann', 'size': 78},
      {'name': 'B. Mee', 'size': 78},
      {'name': 'J. Lingard', 'size': 78},
      {'name': 'K. Trippier', 'size': 78},
      {'name': 'F. Forster', 'size': 77},
      {'name': 'C. Davies', 'size': 77},
      {'name': 'A. Lennon', 'size': 77},
      {'name': 'L. Cattermole', 'size': 77}],
     'name': 'England'},
    {'children': [{'name': 'P. Čech', 'size': 86},
      {'name': 'V. Darida', 'size': 79},
      {'name': 'P. Kadeřábek', 'size': 78},
      {'name': 'B. Dočkal', 'size': 77}],
     'name': 'Czech Republic'},
    {'children': [{'name': 'H. Mkhitaryan', 'size': 85}], 'name': 'Armenia'},
    {'children': [{'name': 'M. Pjanić', 'size': 85},
      {'name': 'E. Džeko', 'size': 84},
      {'name': 'A. Begović', 'size': 82},
      {'name': 'S. Kolašinac', 'size': 80},
      {'name': 'E. Višća', 'size': 79}],
     'name': 'Bosnia Herzegovina'},
    {'children': [{'name': 'R. Bürki', 'size': 84},
      {'name': 'Y. Sommer', 'size': 83},
      {'name': 'S. Lichtsteiner', 'size': 82},
      {'name': 'X. Shaqiri', 'size': 82},
      {'name': 'G. Xhaka', 'size': 82},
      {'name': 'R. Rodríguez', 'size': 81},
      {'name': 'M. Hitz', 'size': 79},
      {'name': 'B. Džemaili', 'size': 78},
      {'name': 'T. Barnetta', 'size': 77},
      {'name': 'V. Behrami', 'size': 77},
      {'name': 'R. Steffen', 'size': 77},
      {'name': 'S. Widmer', 'size': 77}],
     'name': 'Switzerland'},
    {'children': [{'name': 'N. Matić', 'size': 83},
      {'name': 'L. Fejsa', 'size': 82},
      {'name': 'B. Ivanović', 'size': 82},
      {'name': 'D. Tadić', 'size': 80},
      {'name': 'M. Nastasić', 'size': 80},
      {'name': 'S. Milinković-Savić', 'size': 80},
      {'name': 'A. Kolarov', 'size': 79},
      {'name': 'N. Maksimović', 'size': 79},
      {'name': 'A. Ljajić', 'size': 79},
      {'name': 'N. Radoja', 'size': 78},
      {'name': 'F. Kostić', 'size': 78},
      {'name': 'F. Kostić', 'size': 78},
      {'name': 'N. Pejčinović', 'size': 77}],
     'name': 'Serbia'},
    {'children': [{'name': 'G. Sigurðsson', 'size': 82}], 'name': 'Iceland'},
    {'children': [{'name': 'R. Jarstein', 'size': 82},
      {'name': 'M. Elyounoussi', 'size': 78},
      {'name': 'H. Nordtveit', 'size': 77}],
     'name': 'Norway'},
    {'children': [{'name': 'S. Savić', 'size': 82},
      {'name': 'S. Jovetić', 'size': 81}],
     'name': 'Montenegro'},
    {'children': [{'name': 'L. Hrádecký', 'size': 81},
      {'name': 'P. Hetemaj', 'size': 77}],
     'name': 'Finland'},
    {'children': [{'name': 'S. Coleman', 'size': 81},
      {'name': 'J. McCarthy', 'size': 80},
      {'name': 'H. Arter', 'size': 77},
      {'name': 'W. Hoolahan', 'size': 77}],
     'name': 'Republic of Ireland'},
    {'children': [{'name': 'A. Yarmolenko', 'size': 81},
      {'name': 'T. Stepanenko', 'size': 80},
      {'name': 'Y. Rakitskyi', 'size': 80},
      {'name': 'Y. Konoplyanka', 'size': 79},
      {'name': 'A. Pyatov', 'size': 79}],
     'name': 'Ukraine'},
    {'children': [{'name': 'J. Evans', 'size': 79},
      {'name': 'G. McAuley', 'size': 77}],
     'name': 'Northern Ireland'},
    {'children': [{'name': 'E. Hysaj', 'size': 79},
      {'name': 'E. Berisha', 'size': 78}],
     'name': 'Albania'},
    {'children': [{'name': 'F. Andone', 'size': 79},
      {'name': 'S. Radu', 'size': 79},
      {'name': 'C. Tătăruşanu', 'size': 78}],
     'name': 'Romania'}],
   'name': 'Europe'},
  {'children': [{'children': [{'name': 'L. Messi', 'size': 93},
      {'name': 'G. Higuaín', 'size': 90},
      {'name': 'S. Agüero', 'size': 89},
      {'name': 'P. Dybala', 'size': 88},
      {'name': 'A. Di María', 'size': 85},
      {'name': 'M. Icardi', 'size': 84},
      {'name': 'A. Gómez', 'size': 84},
      {'name': 'J. Pastore', 'size': 83},
      {'name': 'E. Garay', 'size': 83},
      {'name': 'E. Banega', 'size': 83},
      {'name': 'L. Biglia', 'size': 83},
      {'name': 'G. Rulli', 'size': 83},
      {'name': 'M. Musacchio', 'size': 83},
      {'name': 'N. Otamendi', 'size': 83},
      {'name': 'M. Rojo', 'size': 82},
      {'name': 'F. Fazio', 'size': 82},
      {'name': 'D. Perotti', 'size': 81},
      {'name': 'M. Lanzini', 'size': 81},
      {'name': 'G. Rodríguez', 'size': 81},
      {'name': 'G. Cabral', 'size': 80},
      {'name': 'I. Piatti', 'size': 80},
      {'name': 'S. Romero', 'size': 80},
      {'name': 'E. Salvio', 'size': 80},
      {'name': 'E. Lamela', 'size': 80},
      {'name': 'F. Belluschi', 'size': 80},
      {'name': 'R. Pereyra', 'size': 80},
      {'name': 'G. Bou', 'size': 79},
      {'name': 'L. López', 'size': 79},
      {'name': 'E. Rigoni', 'size': 79},
      {'name': 'E. Rigoni', 'size': 79},
      {'name': 'P. Zabaleta', 'size': 79},
      {'name': 'C. Ansaldi', 'size': 79},
      {'name': 'L. Vietto', 'size': 79},
      {'name': 'D. Abraham', 'size': 79},
      {'name': 'W. Caballero', 'size': 79},
      {'name': 'F. Fernández', 'size': 79},
      {'name': 'A. Correa', 'size': 79},
      {'name': 'M. Acuña', 'size': 79},
      {'name': 'C. Yacob', 'size': 79},
      {'name': 'D. Valeri', 'size': 79},
      {'name': 'L. Paredes', 'size': 79},
      {'name': 'P. Piatti', 'size': 79},
      {'name': 'N. Tagliafico', 'size': 79},
      {'name': 'I. Marcone', 'size': 79},
      {'name': 'A. Marchesín', 'size': 78},
      {'name': 'R. Funes Mori', 'size': 78},
      {'name': 'R. Funes Mori', 'size': 78},
      {'name': 'E. Sala', 'size': 78},
      {'name': 'A. Marchesín', 'size': 78},
      {'name': 'L. Castro', 'size': 78},
      {'name': 'R. Funes Mori', 'size': 78},
      {'name': 'R. Funes Mori', 'size': 78},
      {'name': 'R. Battaglia', 'size': 78},
      {'name': 'R. Battaglia', 'size': 78},
      {'name': 'A. Ruiz', 'size': 78},
      {'name': 'M. Ruben', 'size': 78},
      {'name': 'D. Benedetto', 'size': 78},
      {'name': 'E. Pérez', 'size': 78},
      {'name': 'F. Cervi', 'size': 78},
      {'name': 'A. Szymanowski', 'size': 78},
      {'name': 'A. Szymanowski', 'size': 78},
      {'name': 'G. Pizarro', 'size': 78},
      {'name': 'J. Pinola', 'size': 77},
      {'name': 'O. Trejo', 'size': 77},
      {'name': 'M. Kranevitter', 'size': 77},
      {'name': 'S. Driussi', 'size': 77},
      {'name': 'R. Martínez', 'size': 77},
      {'name': 'S. Gentiletti', 'size': 77},
      {'name': 'F. Roncaglia', 'size': 77}],
     'name': 'Argentina'},
    {'children': [{'name': 'Neymar', 'size': 92},
      {'name': 'Thiago Silva', 'size': 88},
      {'name': 'Marcelo', 'size': 87},
      {'name': 'Miranda', 'size': 86},
      {'name': 'David Luiz', 'size': 86},
      {'name': 'Alex Sandro', 'size': 86},
      {'name': 'Coutinho', 'size': 86},
      {'name': 'Casemiro', 'size': 85},
      {'name': 'Filipe Luís', 'size': 85},
      {'name': 'Dani Alves', 'size': 84},
      {'name': 'Willian', 'size': 84},
      {'name': 'Oscar', 'size': 83},
      {'name': 'Jonas', 'size': 83},
      {'name': 'Fabinho', 'size': 83},
      {'name': 'Marquinhos', 'size': 83},
      {'name': 'Roberto Firmino', 'size': 83},
      {'name': 'Ederson', 'size': 83},
      {'name': 'Marlos', 'size': 82},
      {'name': 'Raffael', 'size': 82},
      {'name': 'Taison', 'size': 82},
      {'name': 'Douglas Costa', 'size': 82},
      {'name': 'Naldo', 'size': 82},
      {'name': 'Fernandinho', 'size': 82},
      {'name': 'Willian José', 'size': 82},
      {'name': 'Felipe', 'size': 82},
      {'name': 'Lucas', 'size': 82},
      {'name': 'Paulinho', 'size': 81},
      {'name': 'Giuliano', 'size': 81},
      {'name': 'Dante', 'size': 81},
      {'name': 'Gabriel Jesus', 'size': 81},
      {'name': 'Rafinha', 'size': 81},
      {'name': 'Felipe Anderson', 'size': 81},
      {'name': 'Malcom', 'size': 81},
      {'name': 'Jardel', 'size': 80},
      {'name': 'Renato Augusto', 'size': 80},
      {'name': 'Maicon', 'size': 80},
      {'name': 'Sidnei', 'size': 80},
      {'name': 'Eric Botteghin', 'size': 80},
      {'name': 'Ganso', 'size': 80},
      {'name': 'Kaká', 'size': 80},
      {'name': 'Leo Baptistao', 'size': 80},
      {'name': 'Neto', 'size': 80},
      {'name': 'Luiz Gustavo', 'size': 80},
      {'name': 'Jemerson', 'size': 80},
      {'name': 'Allan', 'size': 80},
      {'name': 'Alisson', 'size': 80},
      {'name': 'Fred', 'size': 80},
      {'name': 'Alex Telles', 'size': 80},
      {'name': 'Mariano', 'size': 79},
      {'name': 'Marcelo', 'size': 79},
      {'name': 'Luisão', 'size': 79},
      {'name': 'Anderson Talisca', 'size': 79},
      {'name': 'Maurício', 'size': 79},
      {'name': 'Jonathas', 'size': 79},
      {'name': 'Jonathas', 'size': 79},
      {'name': 'Gabriel Paulista', 'size': 79},
      {'name': 'Soares', 'size': 79},
      {'name': 'Lucas Leiva', 'size': 79},
      {'name': 'Danilo', 'size': 79},
      {'name': 'Bernard', 'size': 79},
      {'name': 'Fernando', 'size': 79},
      {'name': 'Ismaily', 'size': 78},
      {'name': 'Ismaily', 'size': 78},
      {'name': 'Joãozinho', 'size': 78},
      {'name': 'Rafael', 'size': 78},
      {'name': 'Rafinha', 'size': 78},
      {'name': 'Adriano', 'size': 78},
      {'name': 'Rafael', 'size': 78},
      {'name': 'Hilton', 'size': 78},
      {'name': 'Danilo', 'size': 78},
      {'name': 'Danilo', 'size': 78},
      {'name': 'Raúl', 'size': 78},
      {'name': 'Souza', 'size': 78},
      {'name': 'Tiago Volpi', 'size': 78},
      {'name': 'Tiago Volpi', 'size': 78},
      {'name': 'Everticinho', 'size': 77},
      {'name': 'Dalbert', 'size': 77},
      {'name': 'Pedro Henrique', 'size': 77},
      {'name': 'Louri Beretta', 'size': 77},
      {'name': 'Wendell', 'size': 77},
      {'name': 'Rafael Carioca', 'size': 77},
      {'name': 'Claudio Coíntra', 'size': 77},
      {'name': 'Otávio', 'size': 77},
      {'name': 'Bruno César', 'size': 77},
      {'name': 'Vitinho', 'size': 77}],
     'name': 'Brazil'},
    {'children': [{'name': 'L. Suárez', 'size': 92},
      {'name': 'D. Godín', 'size': 88},
      {'name': 'E. Cavani', 'size': 87},
      {'name': 'J. Giménez', 'size': 83},
      {'name': 'F. Muslera', 'size': 82},
      {'name': 'S. Coates', 'size': 81},
      {'name': 'M. Campaña', 'size': 79},
      {'name': 'N. Lodeiro', 'size': 78},
      {'name': 'M. Vecino', 'size': 78},
      {'name': 'G. Ramírez', 'size': 78},
      {'name': 'D. Laxalt', 'size': 78},
      {'name': 'D. Laxalt', 'size': 78},
      {'name': 'M. Lemos', 'size': 77},
      {'name': 'C. Sánchez', 'size': 77}],
     'name': 'Uruguay'},
    {'children': [{'name': 'A. Sánchez', 'size': 89},
      {'name': 'A. Vidal', 'size': 87},
      {'name': 'C. Bravo', 'size': 82},
      {'name': 'G. Medel', 'size': 82},
      {'name': 'F. Orellana', 'size': 80},
      {'name': 'F. Orellana', 'size': 80},
      {'name': 'M. Díaz', 'size': 80},
      {'name': 'P. Hernández', 'size': 80},
      {'name': 'M. Fernández', 'size': 78},
      {'name': 'C. Aránguiz', 'size': 78},
      {'name': 'C. Aránguiz', 'size': 78}],
     'name': 'Chile'},
    {'children': [{'name': 'J. Rodríguez', 'size': 86},
      {'name': 'Falcao', 'size': 84},
      {'name': 'J. Cuadrado', 'size': 82},
      {'name': 'C. Bacca', 'size': 82},
      {'name': 'D. Sánchez', 'size': 81},
      {'name': 'L. Muriel', 'size': 80},
      {'name': 'D. Ospina', 'size': 79},
      {'name': 'J. Murillo', 'size': 79},
      {'name': 'T. Gutiérrez', 'size': 78},
      {'name': 'J. Izquierdo', 'size': 78},
      {'name': 'A. Ramos', 'size': 78},
      {'name': 'D. Zapata', 'size': 78},
      {'name': 'J. Córdoba', 'size': 77}],
     'name': 'Colombia'},
    {'children': [{'name': 'A. Valencia', 'size': 83},
      {'name': 'C. Noboa', 'size': 79},
      {'name': 'F. Caicedo', 'size': 77}],
     'name': 'Ecuador'},
    {'children': [{'name': 'S. Rondón', 'size': 80},
      {'name': 'J. Martínez', 'size': 78}],
     'name': 'Venezuela'},
    {'children': [{'name': 'H. Pérez', 'size': 79},
      {'name': 'M. Almirón', 'size': 79},
      {'name': 'R. Bobadilla', 'size': 78},
      {'name': 'A. Sanabria', 'size': 78}],
     'name': 'Paraguay'},
    {'children': [{'name': 'J. Farfán', 'size': 78}], 'name': 'Peru'}],
   'name': 'South America'},
  {'children': [{'children': [{'name': 'P. Aubameyang', 'size': 88}],
     'name': 'Gabon'},
    {'children': [{'name': 'K. Koulibaly', 'size': 84},
      {'name': 'S. Mané', 'size': 84},
      {'name': 'I. Gueye', 'size': 83},
      {'name': 'K. Baldé Diao', 'size': 82},
      {'name': 'S. Sané', 'size': 79},
      {'name': 'K. Mbodj', 'size': 78},
      {'name': 'K. Mbodj', 'size': 78},
      {'name': "A. N'Diaye", 'size': 78},
      {'name': 'M. Diouf', 'size': 77},
      {'name': 'L. Sané', 'size': 77},
      {'name': 'Y. Sankharé', 'size': 77},
      {'name': 'C. Kouyaté', 'size': 77}],
     'name': 'Senegal'},
    {'children': [{'name': 'M. Benatia', 'size': 84},
      {'name': 'Y. Belhanda', 'size': 81},
      {'name': 'H. Ziyech', 'size': 81},
      {'name': 'K. El Ahmadi', 'size': 80},
      {'name': 'N. Amrabat', 'size': 79},
      {'name': 'S. Boufal', 'size': 79}],
     'name': 'Morocco'},
    {'children': [{'name': 'E. Bailly', 'size': 84},
      {'name': 'Y. Touré', 'size': 83},
      {'name': 'J. Seri', 'size': 82},
      {'name': 'S. Aurier', 'size': 81},
      {'name': 'W. Zaha', 'size': 81},
      {'name': 'S. Kalou', 'size': 80},
      {'name': 'Gervinho', 'size': 79},
      {'name': 'Gervinho', 'size': 79},
      {'name': 'S. Doumbia', 'size': 79},
      {'name': 'W. Bony', 'size': 79},
      {'name': 'M. Gradel', 'size': 77}],
     'name': 'Ivory Coast'},
    {'children': [{'name': 'J. Matip', 'size': 83},
      {'name': "S. Eto'o", 'size': 81},
      {'name': 'C. Kameni', 'size': 80},
      {'name': 'A. Onana', 'size': 78},
      {'name': 'A. Onana', 'size': 78},
      {'name': 'V. Aboubakar', 'size': 78},
      {'name': 'N. Nkoulou', 'size': 78},
      {'name': 'V. Aboubakar', 'size': 78},
      {'name': 'A. Nyom', 'size': 77}],
     'name': 'Cameroon'},
    {'children': [{'name': 'M. Salah', 'size': 83}], 'name': 'Egypt'},
    {'children': [{'name': 'R. Mahrez', 'size': 83},
      {'name': 'I. Slimani', 'size': 82},
      {'name': 'Y. Brahimi', 'size': 82},
      {'name': 'R. Boudebouz', 'size': 81},
      {'name': 'N. Bentaleb', 'size': 80},
      {'name': 'S. Feghouli', 'size': 79},
      {'name': 'F. Ghoulam', 'size': 79},
      {'name': 'A. Mandi', 'size': 78},
      {'name': 'A. Mandi', 'size': 78},
      {'name': 'S. Hanni', 'size': 77}],
     'name': 'Algeria'},
    {'children': [{'name': 'N. Keïta', 'size': 83},
      {'name': 'I. Traoré', 'size': 80},
      {'name': 'A. Diawara', 'size': 77}],
     'name': 'Guinea'},
    {'children': [{'name': 'V. Wanyama', 'size': 82}], 'name': 'Kenya'},
    {'children': [{'name': 'K. Boateng', 'size': 80},
      {'name': 'A. Gyan', 'size': 79},
      {'name': 'A. Ayew', 'size': 79},
      {'name': 'K. Asamoah', 'size': 78},
      {'name': 'A. Baba', 'size': 77}],
     'name': 'Ghana'},
    {'children': [{'name': 'V. Moses', 'size': 79}], 'name': 'Nigeria'},
    {'children': [{'name': 'B. Traoré', 'size': 79}], 'name': 'Burkina Faso'},
    {'children': [{'name': 'Zé Luís', 'size': 79}], 'name': 'Cape Verde'},
    {'children': [{'name': 'Y. Bolasie', 'size': 78}], 'name': 'DR Congo'},
    {'children': [{'name': 'I. Khune', 'size': 77}], 'name': 'South Africa'},
    {'children': [{'name': 'Mexer', 'size': 77}], 'name': 'Mozambique'},
    {'children': [{'name': 'A. Abdennour', 'size': 77}], 'name': 'Tunisia'}],
   'name': 'Africa'},
  {'children': [{'children': [{'name': 'K. Navas', 'size': 85},
      {'name': 'J. Campbell', 'size': 77}],
     'name': 'Costa Rica'},
    {'children': [{'name': 'C. Vela', 'size': 82},
      {'name': 'J. Hernández', 'size': 82},
      {'name': 'J. Corona', 'size': 81},
      {'name': 'J. dos Santos', 'size': 80},
      {'name': 'H. Moreno', 'size': 80},
      {'name': 'A. Guardado', 'size': 80},
      {'name': 'M. Fabián', 'size': 79},
      {'name': 'H. Herrera', 'size': 79},
      {'name': 'G. Ochoa', 'size': 79},
      {'name': 'G. dos Santos', 'size': 79},
      {'name': 'R. Jiménez', 'size': 78},
      {'name': 'M. Layún', 'size': 78},
      {'name': 'H. Lozano', 'size': 78}],
     'name': 'Mexico'},
    {'children': [{'name': 'A. Hutchinson', 'size': 80}], 'name': 'Canada'},
    {'children': [{'name': 'J. Brooks', 'size': 80},
      {'name': 'F. Johnson', 'size': 79},
      {'name': 'M. Bradley', 'size': 78},
      {'name': 'T. Howard', 'size': 78},
      {'name': 'C. Pulisic', 'size': 78},
      {'name': 'C. Pulisic', 'size': 78},
      {'name': 'C. Dempsey', 'size': 78}],
     'name': 'United States'},
    {'children': [{'name': 'O. Alonso', 'size': 77}], 'name': 'Cuba'},
    {'children': [{'name': 'W. Morgan', 'size': 77}], 'name': 'Jamaica'}],
   'name': 'North America'},
  {'children': [{'children': [{'name': 'S. Kagawa', 'size': 83},
      {'name': 'T. Inui', 'size': 78},
      {'name': 'K. Honda', 'size': 78},
      {'name': 'Y. Ōsako', 'size': 77}],
     'name': 'Japan'},
    {'children': [{'name': 'O. Toprak', 'size': 83},
      {'name': 'A. Turan', 'size': 82},
      {'name': 'M. Topal', 'size': 80},
      {'name': 'O. Özyakup', 'size': 80},
      {'name': 'Y. Mallı', 'size': 79},
      {'name': 'V. Babacan', 'size': 79},
      {'name': 'E. Çolak', 'size': 79},
      {'name': 'N. Şahin', 'size': 79},
      {'name': 'E. Belözoğlu', 'size': 79},
      {'name': 'H. Çalhanoğlu', 'size': 79},
      {'name': 'B. Yılmaz', 'size': 78},
      {'name': 'C. Tosun', 'size': 78},
      {'name': 'M. Ekici', 'size': 77}],
     'name': 'Turkey'},
    {'children': [{'name': 'H. Son', 'size': 82}], 'name': 'Korea Republic'},
    {'children': [{'name': 'Mário Fernandes', 'size': 81},
      {'name': 'A. Dzagoev', 'size': 80},
      {'name': 'O. Shatov', 'size': 80},
      {'name': 'F. Smolov', 'size': 80},
      {'name': 'I. Smolnikov', 'size': 79},
      {'name': 'A. Samedov', 'size': 79},
      {'name': 'V. Berezutskiy', 'size': 79},
      {'name': 'I. Akinfeev', 'size': 79},
      {'name': 'I. Denisov', 'size': 79},
      {'name': 'S. Kritsyuk', 'size': 79},
      {'name': 'A. Kokorin', 'size': 79},
      {'name': 'D. Cheryshev', 'size': 78},
      {'name': 'D. Cheryshev', 'size': 78},
      {'name': 'A. Dzyuba', 'size': 78},
      {'name': 'D. Glushakov', 'size': 78},
      {'name': 'Guilherme', 'size': 78},
      {'name': 'S. Ignashevich', 'size': 78},
      {'name': 'Guilherme', 'size': 78},
      {'name': 'A. Lunev', 'size': 78},
      {'name': 'S. Ryzhikov', 'size': 78},
      {'name': 'A. Berezutskiy', 'size': 77}],
     'name': 'Russia'},
    {'children': [{'name': 'V. Denisov', 'size': 80}], 'name': 'Uzbekistan'},
    {'children': [{'name': 'O. Al Soma', 'size': 78},
      {'name': 'O. Al Soma', 'size': 78}],
     'name': 'Syria'},
    {'children': [{'name': 'S. Azmoun', 'size': 77}], 'name': 'Iran'}],
   'name': 'Asia'},
  {'children': [{'children': [{'name': 'W. Reid', 'size': 79}],
     'name': 'New Zealand'}],
   },
  {'children': [{'children': [{'name': 'B. Jones', 'size': 77}],
    }],
   'name': 'Australia Oceania'}],
 'name': 'DISTRIBUTION OF TOP 1000 PLAERS DUE TO NATIONALITY'}
}